name: minimal
description: Minimal project


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  google_fonts: ^3.0.1
  get_it: ^7.2.0
  dio: ^4.0.6
  flutter_secure_storage: ^5.0.2
  mockito: ^5.2.0
  pretty_dio_logger: ^1.1.1
  flutter_svg: ^1.1.0
  lottie: ^1.3.0
  file_picker: ^4.6.1
  dotted_border: ^2.0.0+2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/
    - assets/circle_0.png
    - assets/circle_1.png
    - assets/circle_2.png
    - assets/minimal.png
    - assets/progress.json